---
# tasks file for nullmailer
#
- name: prepare config dir
  file:
    path: /etc/nullmailer
    state: directory
    mode: 0755
  become: yes

- name: configure generic mail settings
  template:
    src: mailname.j2
    dest: /etc/mailname
    mode: '644'
  notify: restart_nullmailer
  become: yes

- name: configure nullmailer
  template:
    src: '{{ item.name + ".j2" }}'
    dest: /etc/nullmailer/{{ item.name }}
    mode: '{{ item.mode | default("644") }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
  with_items:
    - name: adminaddr
    - name: defaultdomain
    - name: defaulthost
    - name: helohost
    - name: idhost
    - name: pausetime
    - name: remotes
      group: mail
      mode: '640'
    - name: sendtimeout
  notify: restart_nullmailer
  become: yes

- name: install
  apt:
    name: nullmailer
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
